[project]
name = "mlops-agentic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "browser-use>=0.1.40",
    "fastapi[standard]>=0.115.7",
    "google-genai==0.5.0",
    "isort>=6.0.0",
    "jinja2>=3.1.5",
    "langchain-google-genai==2.0.8",
    "llama-index>=0.12.17",
    "llama-index-embeddings-gemini>=0.3.1",
    "llama-index-llms-gemini>=0.4.10",
    "lmnr[all]>=0.4.59",
    "loguru>=0.7.3",
    "mistralai==0.4.2",
    "pillow>=10.4.0",
    "pydantic>=2.10.3",
    "pylint>=3.3.4",
    "redis>=5.2.1",
    "ruff>=0.9.3",
    "speechrecognition>=3.14.1",
    "websockets>=14.2",
]
